Vagrant.configure("2") do |main|
  main.vm.box = "alvistack/ubuntu-22.04"

  main.vm.provision "shell", inline: "echo Hello"
#  config.vm.define "app" do |app|
#    #app.vm.box = "centos"
#    app.vm.network "forwarded_port", guest: 1111, host: 11111, host_ip: "192.168.1.34"
#    app.vm.network "private_network", ip: "192.168.10.12", netmask: "255.255.255.0", auto_config: true
#  end

#  config.vm.define "db" do |db|
#    #db.vm.box = "centos"
#    db.vm.network "private_network", ip: "192.168.10.13", netmask: "255.255.255.0", auto_config: true
#  end
end
