Vagrant.configure("2") do |config|

  # => Master Box
  config.vm.define "master" do |master|
    master.vm.box = "generic/ubuntu2010"
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "10.0.0.2", netmask: "255.255.255.0", auto_config: true
  end

  # => Slave Box
  config.vm.define "slave" do |slave|
    slave.vm.box = "generic/ubuntu2010"
    slave.vm.hostname = "slave"
    slave.vm.network "private_network", ip: "10.0.0.5", netmask: "255.255.255.0", auto_config: true
  end

end
